### ISSUE TITLE
[Enhancement] Custom Resource Dir Constructor

### ISSUE THREAD

**Issue by jredfox** [lumien231/Resource-Loader#1]
The constructor for your IResourcePack should contain the base root directory and maybe more options like where to look what directory base should this be? I would have used this as a dependency but, I discovered I had to copy then re-write over half of it to get it to work for a different file location.

So basically just make it more dynamic so more people will use it as a dependency because they can change their location.

Not sure if that's what you were going for but, your code could easily be converted into that

**Comment by lumien231** [comment]
It's meant to be a way for **users** to load custom resources for other mods into the game. Different locations for different mods seem kinda unnecessary.

**Comment by jredfox** [comment]
well don't you think you should be an api and let modders decide where the dir is here take a look at my implementation for an IResourcePack. I don't have the manual refresh working yet for anything except lang maybe you could tell me how to refresh a resource pack and only a my resource pack. 
https://github.com/jredfox/evilnotchlib/blob/master/src/main/java/com/EvilNotch/lib/util/minecraft/content/client/rp/CustomResourcePack.java

**Comment by lumien231** [comment]
But why? Users can put resources for any mod that needs them into one folder, what advantage would splitting them up have?

**Comment by jredfox** [comment]
loading them externally to a seperate location so when you have custom main menu then another mod says hey I don't want this to get confused with custom main menu I want this in mods/resourcepacks or config/resourcepacks or config/mymodfolder/resourcepack

And if the mod won't get confused on which is which there is always the end user getting confused on what goes where and what isn't custom main menu. In my example I put it under the last option I gave

**Comment by lumien231** [comment]
Resources aren't mod specific though, users can seperate them in different folders if they want to.

**Comment by jredfox** [comment]
ok do what you want just a suggestion from modder to modder
